#!/bin/bash
# -*- coding: utf-8 -*-

SERVICE_DOMAIN='pds.3wx.ru'

rm -rf /home/docker/gateway/sites-data/${SERVICE_DOMAIN}/*

tar -xzf front.tar.gz --one-top-level=/home/docker/gateway/sites-data/${SERVICE_DOMAIN}
chown docker:docker -R /home/docker/gateway/sites-data/${SERVICE_DOMAIN}

rm -f front.tar.gz ${BASH_SOURCE}

docker exec gateway /init reload

exit 0
