#!/usr/bin/env bash

function cleanup() {
  echo "caught Signal ... stopping application ..."

  kill -s SIGINT $(cat /var/run/node.pid)

  echo "done."
  exit 0
}

trap cleanup SIGINT SIGHUP SIGQUIT SIGKILL SIGTERM

if [[ -z "$@" ]]; then
  rm -f /var/run/node.pid
  #yarn --cwd /build startp
  cd /build
  NODE_ENV=production node src/index.mjs
  exit $?

elif [[ "$@" == "test" ]]; then
  yarn --cwd /build test
  exit $?
fi

exec "$@"
