#!/usr/bin/env bash

cleanup() {
  echo "caught Signal ... stopping application ..."

  killall -HUP node

  echo "done."
  exit 0
}

trap cleanup HUP

if [[ -z "$@" ]]; then
  yarn --cwd /build startp
  exit $?

elif [[ "$@" == "test" ]]; then
  yarn --cwd /build test
  exit $?
fi

exec "$@"
