#!/bin/bash
# -*- coding: utf-8 -*-

remote_server=web@3wx.ru

set -e

deploy() {
  echo "deploy"

  echo "building container ..."
  docker build -t pds_api .

  echo "compressing container ..."
  docker save api:latest | gzip > api_latest.tar.gz

  echo "sending files to remote server ..."
  scp api_latest.tar.gz docker-compose.yml setup $remote_server:~

  rm -f api_latest.tar.gz

  echo "setting up ..."
  ssh -t $remote_server "sudo ./setup"

  echo -e "\033[1;32mdone\033[0m"

  exit 0
}

deploy
