version: '3'

services:
  pds_api:
    image: pds_api:latest
    container_name: pds_api
    hostname: pds_api
    volumes:
      - ./log:/log
    networks:
      - gateway

networks:
  gateway:
    external: true
