#!/bin/bash
# -*- coding: utf-8 -*-

set -e

SERVICE_NAME='pds_api'

docker load < api_latest.tar.gz

rm -f api_latest.tar.gz ${BASH_SOURCE}

chown docker:docker -R docker-compose.yml
mv docker-compose.yml /home/docker/${SERVICE_NAME}/

cd /home/docker/${SERVICE_NAME} || exit 1
docker-compose up -d --build --remove-orphans

docker update --restart always ${SERVICE_NAME}

docker image prune -af

exit 0
